# Configuración del puerto del microservicio
quarkus.http.port=9083

# Configuración de base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=scratchuser
quarkus.datasource.password=scratchpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/transaction_service_db
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.log.category."org.hibernate.SQL".level=DEBUG

# Configuración de JWT para Quarkus
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=customer-service
mp.jwt.token.header=Authorization
mp.jwt.token.cookie=
mp.jwt.token.schemes=Bearer

quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG

# Esto le indica a Quarkus que no intente levantar un broker Kafka embebido
quarkus.kafka.devservices.enabled=false

# Configuración de Kafka para transaction-service
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
mp.messaging.connector.smallrye-kafka.security.protocol=PLAINTEXT
mp.messaging.connector.smallrye-kafka.auto.offset.reset=earliest
mp.messaging.connector.smallrye-kafka.enable.idempotence=true
mp.messaging.connector.smallrye-kafka.acks=all
mp.messaging.connector.smallrye-kafka.retries=10
mp.messaging.connector.smallrye-kafka.request.timeout.ms=30000
mp.messaging.connector.smallrye-kafka.max.in.flight.requests.per.connection=5

# Configuración de los topics de salida
mp.messaging.outgoing.transactions-completed.connector=smallrye-kafka
mp.messaging.outgoing.transactions-completed.topic=transactions.completed
mp.messaging.outgoing.transactions-completed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.transactions-failed.connector=smallrye-kafka
mp.messaging.outgoing.transactions-failed.topic=transactions.failed
mp.messaging.outgoing.transactions-failed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Si se agregan producers en el futuro, ejemplo:
# mp.messaging.outgoing.account-events.connector=smallrye-kafka
# mp.messaging.outgoing.account-events.topic=account.events
# mp.messaging.outgoing.account-events.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
# mp.messaging.outgoing.account-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer

# Configuración del RestClient para account-service
org.eclipse.microprofile.rest.client.propagateHeaders=Authorization
account-service-api/mp-rest/url=http://localhost:9082
account-service-api/mp-rest/scope=javax.inject.Singleton